### PR TITLE
Seamlessly removing the use of backingpath for sub and attach.

### PR DESCRIPTION
**Pull request by privefl**
So,
- I added a function to get the directory where a FileBackedBigMatrix is stored,
- I added this info to the description object

so that now, you can use `sub.big.matrix` and `attach.big.matrix` without specifying the `backingpath` parameter (you still can for backward compatibility).

There are lots of man files that have been modified (without real change in the documentation) due to the use of the latest version of [roxygen2](https://github.com/klutometis/roxygen).

You can see the new test file if it's not clear enough.

### CODE REVIEW

**Comment by privefl** [comment]
_Wow ok, I've just understood that this PR update whenever I update my repo._

So, if you want I added a method to efficiently **transpose** a `big.matrix`.

**Comment by cdeterman** [comment]
Hi @privefl, with transpose you are more in my territory with bigalgebra. My fork is the most recent. Please compare yours to the version I have with the armadillo backend. Things like transpose belong in that package.

**Comment by privefl** [comment]
Hi @cdeterman, I've tested matrix multiplication with Armadillo backend and it is very slow (compared for example with Eigen, or directly by blocks within R). 
It is why I don't use `bigalgebra`, because I really care about performances.

Moreover, I'm not sure that `transpose` is only used for algebra. For example, when parsing some data and storing it in a `big.matrix`, it may be easier (and even faster) to read the transposed matrix (and transpose it afterwards). 

As you (and Mike) prefer.

**Comment by cdeterman** [comment]
I agree that the default is quite slow but that depends entirely on the BLAS backend being used which by default is the R BLAS which is not very good. If you use OpenBLAS or ATLAS it is much better. This flexibility is the reason armadillo was chose and not Eigen or our own custom scripts.

As for the proper place of transpose this discussion happened before hence why I made the statement here. That said if the others agree it would be better here I wouldn't argue.

**Comment by privefl** [comment]
I'll redo some testing (for matrix multiplication) and open an issue in `bigalgebra`.

**Comment by cdeterman** [comment]
@kaneplusplus Not to be a stickler but did you want the entire merge here?  I am mainly referring to the addition of `transpose`.  I thought we had discussed previously that it should be in `bigalgebra`?  Ultimately I don't care that much but it does matter whether I keep `transpose` functionality in `bigalgebra` going forward.

**Comment by privefl** [comment]
If you don't want the `transpose` feature in this package, just remove the corresponding files in 
- R/
- src/
- examples/
- tests/testthat/
- man/

They should be independent files.

**Comment by kaneplusplus** [comment]
@cdeterman Thanks for pointing this out. I'll remove now.

**Pull request merged**
