### PR TITLE
bigmemory rcpp update

### PR DESCRIPTION
**Pull request by cdeterman**
There are quite a few changes in this merge request.  Generally speaking, this is a conversion of the original bigmemory package to now utilize Rcpp and roxygen2.  It has been structured in the same format described by rOpenSci (i.e. man-roxygen directory).  I have also converted the unit tests over to the more user-friendly testthat framework and added more tests to make sure all the updates I made didn't break anything.  There are naturally some updates to the DESCRIPTION file for the additional packages (i.e. Rcpp) but also added the Biarch option so that windows systems will install both architectures by default (this was a problem when trying to install additional packages like bigalgebra).  Lastly, there are also some small changes to the header statements in the cpp files.  Rcpp contains most of the headers so they have been drastically simplified.  There is also a small undef statment to accomodate the RcppArmadillo implementation of bigalgebra (pull request will be forthcoming).  Please feel free to take your time reviewing these changes.  I hope you will find these updates valuable.

### CODE REVIEW

**Comment by cdeterman** [comment]
I know you are likely very busy too and there was quite a bit here but was wondering if you had a chance look over these changes to implement `Rcpp`, `roxygen2` and `testthat` for `bigmemory`?  I perfectly understand if you disagree with the changes but I would be very happy to discuss anything that seems strange or incorrect to you.

**Comment by kaneplusplus** [comment]
I'm sorry I missed the original pull request. Can you give me the weekend to look through it? I need to check with Peter Haverty to make sure it won't affect anything the guys at Genentech are working on. Please feel free to email me or ping me anytime if I'm slow with a request.

**Comment by cdeterman** [comment]
Sure, there is no rush.  I am happy if I can help improve these packages.  I don't believe it should break anything.  All the functions, at least everything I tested, appears to work exactly as before.  Let me know what your thoughts are.

**Comment by kaneplusplus** [comment]
This looks awesome. Great job.

**Pull request merged**
