### PR TITLE
Simple fix for the failure of the tests under RStudio

### PR DESCRIPTION
**Pull request by adamryczkowski**
Small and trivial one.

### CODE REVIEW

**Comment by adamryczkowski** [comment]
This wasn't about changing coverage. Without it, R under RStudio on my Ubuntu Linux 14.04 64bit simply didn't find the 'iris' database. That's all.

**Comment by adamryczkowski** [comment]
Added fix for #42

**Comment by privefl** [comment]
Wow, sorry to say it like this but I'm REALLY disappointed...

Two things:
 - This change supposes that people are more likely to use 128 than -1 (just an example)
 - And putting the NA to 0? 255 I would understand, but...

I have been using bigmemory to store genotype matrices (only 0, 1, 2 or NA) with the type `char` for several months now and this change totally break all my code.

If you want to use `as.raw(130)`, just use two bytes with type `short`, please.

I (and maybe many people) would really be grateful if bigmemory's people could revert that merge.

Best regards, 
Florian

**Comment by adamryczkowski** [comment]
On 13.09.2016 21:30, Florian Privé wrote:
>
> Wow, sorry to say it like this but I'm REALLY disappointed...
>
> Two things:
>
>   * This change supposes that people are more likely to use 128 than
>     -1 (just an example)
>   * And putting the NA to 0? 255 I would understand, but...
>
> I have been using bigmemory to store genotype matrices (only 0, 1, 2 
> or NA) with the type |char| for several months now and this change 
> totally break all my code.
>
I think you don't understand this patch. Before the patch, nobody was 
affectively able to store *either 128 or -1* in raw (char) big.matrix. 
(Technically speaking, you would store it, but you will be unable to 
retrieve it later, as it would be silently converted to NA, which was 
0). Just take a look at the attached unit tests. Did you really use the 
'char' type of the big.matrix?


> If you want to use |as.raw(130)|, just use two bytes with type 
> |short|, please.
>
It is not really a good walkaround. There is no representation of short 
in R. And even if there was, how would you de-serialize vector of 
shorts? What about endiannes, that vary between machines?

And - why keep char anyway if it was broken? My patch simply made 'char' 
type usable.

If you have any idea about alternative implementation of storage "raw" 
vectors in big.matrix, than please share it.

**Comment by privefl** [comment]
```
a <- big.matrix(4, 4, type = "char")
a[1, 1] <- -1
a[1, 1]
```
gave 
`[1] -1`

I don't understand your point. 

I don't use "raw" storage so I don't know how to fix YOUR problem.

What I say is there are people that use bigmemory type "char" to store small integers to save space (and increase speed) and your change is breaking all their code that has been here for months.

**Comment by adamryczkowski** [comment]
OK. Now I understand what you mean. You argue, that this patch changed the following existing behaviour. Supose, 

```
m<-bigmemory::big.matrix(2,1,type='char')

m[1,1]<-240
m[2,1]<- -5
```

Prior behaviour was
```
> m[1:2,1]
[1] NA -5
```

and now it is

```
> m[1:2,1]
[1] 240 NA
```

That's a fair point. 

@kaneplusplus What about adding *another* type for the bigmemory, type "raw" (or "byte")? Then we could live the 'char' incompatible with raw as it was originally and don't brake any code. What do you think?

**Comment by privefl** [comment]
Seems fair to me.

Thanks for understanding my point.

**Comment by adamryczkowski** [comment]
I expect the patch would be ready in a few hours (but I can't promise). I take the name "raw" to signify compatibility with the R "raw" data type.

**Comment by adamryczkowski** [comment]
Here is my patch: https://github.com/kaneplusplus/bigmemory/pull/43

**Comment by kaneplusplus** [comment]
Thanks very much Adam. I don't have a good handle on who (if anyone) uses anything other than integers and doubles. It's good to get this information.

**Pull request merged**
