### PR TITLE
Fix low test coverage

### PR DESCRIPTION
**Pull request by cdeterman**
There was some memory issues with the -O0 flag used by `covr`.  This was in turn caused by some uninitialized variables.  Fixing those solved the problem and should address issue #46.

### CODE REVIEW

**Comment by privefl** [comment]
Nice!

**Comment by kaneplusplus** [comment]
This is great. Thanks very much @privefl.

**Comment by privefl** [comment]
No, no it's @cdeterman that did all the work. 
I was just complimenting him.

**Comment by kaneplusplus** [comment]
Oops! Thanks @cdeterman.

**Pull request merged**
