### PR TITLE
non-continuous element support

### PR DESCRIPTION
**Pull request by cdeterman**
Previously users could only index single elements or contiguous regions for simple functions like read/write (e.g. `bm[1:3,1:3]`).  These new changes allow users to index non_contiguous elements that mirror the normal R matrix/data.frame syntax for use cases such as `bm[c(1,2,5)]` or `bm[c(2,4)] <- 42`.  Relevant unit tests have been added.

### CODE REVIEW

**Comment by cdeterman** [comment]
FYI, you may notice that coverage has decreased significantly but this is because coveralls is now also looking through all the C++ files as well as the R files.

**Comment by cdeterman** [comment]
Something actually seems off here, somehow coveralls isn't recognizing anything.  I will keep looking into this.  Everything still functions correctly though.

**Comment by kaneplusplus** [comment]
Please note that you could index non-contiguous subsets. You can not create a ```sub.big.matrix``` on a non-contiguous subset.

**Comment by cdeterman** [comment]
@kaneplusplus these changes aren't for subsets.  They are just for access to individual elements.

**Comment by kaneplusplus** [comment]
My mistake, thanks for the clarification.

**Pull request merged**
