### PR TITLE
remove warnings by reordering headers

### PR DESCRIPTION
**Pull request by eddelbuettel**
This covers only one of the two files emitting a fair amount of warnings. I'll try to get to the other one too.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
It is driving me a little batty that I cannot get of the warnings when compiling `src/BigMemory.cpp`. Hm.

**Comment by kaneplusplus** [comment]
Many thanks!

**Comment by eddelbuettel** [comment]
Oh, you were too fast.  I figured it out and wanted to expand the PR but somehow it did not let me -- so just sent you a new one.

**Comment by kaneplusplus** [comment]
OK, sounds good.

**Comment by eddelbuettel** [comment]
Is this ok / expected or an issue:  https://travis-ci.org/kaneplusplus/bigmemory/builds/86677806  ?

**Comment by kaneplusplus** [comment]
I think it's a coveralls issue. I usually hit restart the build until it works or gives a more definitive error related to the packages.

**Comment by eddelbuettel** [comment]
I may be blind but I do not see the 'retickle this' button...

**Comment by kaneplusplus** [comment]
It's on the right under settings. I've restarted.

**Comment by eddelbuettel** [comment]
I looked, I only see 'requests' -- may be different for you as "owner".

**Comment by kaneplusplus** [comment]
That's probably right. Thanks again, I've merged the second pull request. It's building without problems on Linux and I built it on my Mac. This was extremely helpful.

**Comment by eddelbuettel** [comment]
My pleasure -- I much prefer clean builds too :)

**Pull request merged**
